### ISSUE TITLE
Легаси Алевардыча

### ISSUE THREAD

**Issue by Arzangulyan** [profcomff/.github#114]
1. Рефакторинг аутха
    - [x] Фикс гонки в аутхе
    - [x] Рефакторинг кафки
2. [x] Дока по серверному администрированию
    - Kafka
    - Caddy
    - Postgres
    - Airflow
    - cicd
    - file.d
    - частые действия
    - Настройка кронджобов, тг сообщений о входе
3. [x] Дока по dns на r01
5. [x]  Дока по сайту профкома 
6. [x] Дока по print api
7. [x] Дока timetable api
8. [x] Перенести всю доку в docs
9. [x] Актуализировать доку по бэку
10. [x] Улучшить документацию по миграциям
11. [x] Работа с PyPi и Github Docker Registry
12. [x] Работа с CI/CD

**Comment by grigoriev-semyon** [comment]
Документация по timetable-api, оказывается, уже написана: https://github.com/profcomff/timetable-api?tab=readme-ov-file
