### ISSUE TITLE
Опросы пользователей через модалку

### ISSUE THREAD

**Issue by Arzangulyan** [profcomff/.github#123]
Нужен внутренний сервис (желательно для многократного использования), который позволил бы вкидывать юзерам при первом открытии приложения (например, в неделю) модалку с мини-опросом. Вопросы либо на множественный выбор, либо на текст из нескольких слов.   

Это нужно для проведения количественных CSI опросов о приложении и сбора обратной связи  

Задача предполагает: 
- [ ] Дизайн модалки и вопросов 
- [ ] Реализацию на фронте 
- [ ] Ручки на бэке для создания таких опросов и их запуска

Возможно тут бы жилось проще с какой-нибудь примитивной админкой таких штук, чтобы не создавать опросы через сваггер, но это делает задачу еще более сложной. Возможно для первого пилотного запуска можно даже без бэка запустить все
