### ISSUE TITLE
Сверстать админку

### ISSUE THREAD

**Issue by MarkShidran** [profcomff/.github#151]
- [ ] profcomff/admin-ui#5 
- [ ] profcomff/admin-ui#4 
- [ ] profcomff/admin-ui#3 
- [x] profcomff/webapp-ui#148
