### ISSUE TITLE
Мероприятия с регистрацией

### ISSUE THREAD

**Issue by viribus-issue-bot** [profcomff/.github#154]
Добавить возможность создавать мероприятия, которые не привязаны к академическим группам и по умолчанию не отображаются в календарях пользователей. 

На фронте их можно будет открывать по прямой ссылке на мероприятие. Для незалогина будет серая кнопка "для регистрации войдите в приложение", для залогина кнопка "регистрация", для зарегистрированного на мероприятия залогина – "я не приду". 

- [ ] Добавить мероприятиям признак "Разрешить регистрацию"
- [ ] Добавить новые методы для регистрации и отмеры регистрации на событие (отдельная табличка с отношением event_id-user_id)
- [ ] Добавить в ответ API "мероприятие" с признаком "Разрешить регистрацию" поле "Пользователь зарегистрирован"
- [ ] Добавить в ответ API "все мероприятия" мероприятия, на которые пользователь зарегистрирован
- [ ] Добавить кнопку "Зарегистрироваться" на фронте
- [ ] Опционально. Добавить на мероприятие скоупы пользователей, которые могут это мероприятие видеть. Если у пользователя нет нужного скоупа, он будет получать 404 на <code>GET /event/{id}</code>
> Issue open by Roman Dyakov via <a href="https://t.me/c/1758480664/22810/46098">telegram message.</a>
