### ISSUE TITLE
Переход на Pydantic v2

### ISSUE THREAD

**Issue by dyakovri** [profcomff/.github#53]
Pydantic обновился до второй версии, написанной на Rust, нужно поддержать переход в наших сервисах

## Python, uses pydantic
- [x] profcomff/fastapi-template#12
- [x] profcomff/converter-api#11
- [x] profcomff/rating-api#2
- [x] profcomff/cicd-api#14
- [x] profcomff/social-api#6
- [x] profcomff/aciniformes-project#6
- [x] profcomff/auth-lib#34
- [x] profcomff/timetable-api#97
- [x] profcomff/print-api#58
- [x] profcomff/marketing-api#19
- [x] profcomff/print-vkbot#21
- [x] profcomff/print-tgbot#61
- [x] profcomff/issue-github-tgbot#231
- [x] profcomff/userdata-api/pull/5
- [x] profcomff/auth-api/pull/138
- [x] profcomff/services-api#42

## Python, no pydantic
- profcomff/dwh-pipelines
- profcomff/logging-lib
- profcomff/preparation-timetable-data
