### ISSUE TITLE
Обработка персональных данных

### ISSUE THREAD

**Issue by Arzangulyan** [profcomff/.github#64]
- [x] проконсультироваться с юристами 
- [x] составить политику обработки перс. данных
- [ ] если необходимо, внести организацию в реестр операторов перс. данных на [сайте](https://pd.rkn.gov.ru/operators-registry/notification/form/) 
- [x] https://github.com/profcomff/webapp-ui/issues/130
- [x] Добавить ее во фронт страниц авторизации

**Comment by annndruha** [comment]
А это какое-то требование государства чтобы все там были?

**Comment by Arzangulyan** [comment]
@annndruha, у Тильды есть страница, где прописано мно чего про законы в отношении операторов персональных данных: https://tilda.education/articles-personal-data-law

Сейчас я консультируюсь с юристами из юридической клиники МГУ. Они нам помогут и с корректным составлением политики и учетом прочих законодательных тонкостей

**Comment by Arzangulyan** [comment]
Ожидается ответ от юристов

**Comment by Arzangulyan** [comment]
Прислали новую версию. Надо ее перечитать и внести свои правки
