### ISSUE TITLE
Царь-база данных

### ISSUE THREAD

**Issue by Arzangulyan** [profcomff/.github#86]
Надо собрать все данные в одном месте и потом их разложить так, чтобы нужные данные в dwh на постоянке обновлялись и были связаны друг с другом. Ну и чтобы в этих данных могли разобраться все потребители. Это потом можно использовать в приложении, в аналитике и просто предоставлять данные по запросу 

### План работы

1. Собрать эти данные (начнем с основных: соберём данные из наших апишек + БД профсоюза). В целом, это один шаблон и десяток дагов из него, чтобы данные из баз данных апишек передать а базы данных

2. Обработать данные, чтобы очистить их от мусора, собрать какую-нибудь историю изменений и так далее

3. Найти важные объекты среди этих данных и связи между этими объектами. Нарисовать схему данных, определив нормализацию, частоту обновления/дополнения, сбалансировать гранулярность данных 

4. Придумать варианты использования этих данных и описать их

5. На основе отрисованной схемы в пункте 3 схемы создать DDS таблицы, пайплайны эирфрлоу. Важно не забывать тут писать параллельно документацию. Приоритет выстроить после п.4.

6. Реализовать прикладные использования из п.4 (параллельно с п.6)

#### Пункт 1

- [x] profcomff/dwh-definitions#18
- [x] profcomff/dwh-pipelines#37
- [x] profcomff/dwh-pipelines#38
- [ ] Продумать варианты использования в сервисах

#### Пункт 2

- [ ] profcomff/dwh-pipelines#39
- [ ] profcomff/dwh-pipelines#40

#### Пункт 3

- [ ] profcomff/dwh-definitions#19
- [ ] profcomff/.github#94
- [ ] profcomff/dwh-pipelines#41

#### Пункт 4

- [ ] Создать DDS таблицы
- [ ] Создать пайплайны airflow

#### Пункт 6

- [ ] Перевести все на новую базу данных все репозитории (потенциально эпик)

**Comment by Arzangulyan** [comment]
@Wudext @parfenovma 
Этот тикет ваще актуален еще?)

**Comment by Wudext** [comment]
Нет

**Comment by Arzangulyan** [comment]
> Нет

Тогда закрываем
